[package]
name = 'spec_test_utils'
version = '0.1.0'
edition = '2018'

[dependencies]
derive_more = '0.99.11'
serde = { version = '1.0.116', features = ['derive'] }
serde_repr = '0.1.6'
serde_yaml = '0.8.13'
ssz_new = { path = '../utils/ssz_new' }
