[package]
name = 'anyhow_stable_backtrace'
version = '0.1.0'
edition = '2018'

[lib]
name = 'anyhow'

[dependencies]
backtrace = '0.3.51'
derive_more = '0.99.11'
original_anyhow = { package = 'anyhow', version = '1.0.33' }
