[package]
name = 'ssz_new'
version = '0.1.2'
authors = ['Faustas <faustas.butkus@gmail.com>']
edition = '2018'

[dependencies]
eth2_ssz_types = '0.2.0'
ethereum-types = '0.9.2'
thiserror = '1.0.21'
typenum = '1.12.0'

[dev-dependencies]
ssz_new_derive = { path = '../ssz_new_derive' }
